name: MarioKart
main: net.stormdev.mario.mariokart.main
version: 3.1
softdepend: [Vault]
depend: [uCars]
commands:
   marioRaceAdmin:
        aliases: [mra, marioadmin]
        description: This is the setup of racetracks and admin commands
        usage: /<command> [Create <TrackName> <Laps>] [Delete <TrackName>] [List (Page)] [setLaps <TrackName> <Laps>]
        permission: mariokart.raceadmin
        permission-message: You don't have access to this command
        default: op
   race:
        description: This is the playing of race tracks
        usage: /<command> [List (Page)] [Join <Track> (GameType "Race"/"Timed"/"Cup")] [Leave] [Queues] [Shop]
        permission: mariokart.race
        permission-message: You don't have access to this command
        default: true
   racetimes:
        description: Shows the top X race times for a track.
        usage: /<command> <TrackName> <Amount>
        permission: mariokart.race
        permission-message: You don't have access to this command
        default: true