package net.stormdev.mariokartAddons;

public enum Action {
	HIT_BANANA, EARN_POWERUP, DEPLOY_BANANA, STAR, BOOST, DEPLOY_BOMB, DEPLOY_LIGHTNING, FIRE_BLUE_SHELL, FIRE_RED_SHELL, FIRE_GREEN_SHELL, FIRE_FREEZE, HIT_BY_SHELL, STRUCK_BY_LIGHTNING, UNKNOWN
}
